<link href="{{ asset('/main/boots.css') }}" rel="stylesheet">
<link href="{{ asset('/main/fontawesome6.5.1/css/all.css') }}" rel="stylesheet">
<link href="{{ asset('/main/fontawesome6.5.1/css/brands.css') }}" rel="stylesheet">
<link href="{{ asset('/main/fontawesome6.5.1/css/fontawesome.css') }}" rel="stylesheet">
<link href="{{ asset('/main/fontawesome6.5.1/css/regular.css') }}" rel="stylesheet">
<link href="{{ asset('/main/fontawesome6.5.1/css/solid.css') }}" rel="stylesheet">
<link href="{{ asset('/main/fontawesome6.5.1/css/svg-with-js.css') }}" rel="stylesheet">
<link href="{{ asset('/main/fontawesome6.5.1/css/v4-font-face.css') }}" rel="stylesheet">
<link href="{{ asset('/main/fontawesome6.5.1/css/v4-shims.css') }}" rel="stylesheet">
<link href="{{ asset('/main/fontawesome6.5.1/css/v5-font-face.css') }}" rel="stylesheet">
